config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to => 'homes#top'
  get '/home/about' => 'homes#show'

  resources :users, only:[:index,:show,:edit,:update,:create]
  resources :books, only:[:new,:create,:index,:show,:edit,:update,:destroy]
  resources :relationships, only:[:create,:destroy]
  resources :books, only:[:new,:create,:index,:show,:destroy] do
  	resource :favorites, only:[:create, :destroy]
  	resource :book_comments, only:[:create,:destroy]
  end
  get '/followers/:id' => 'relationships#userfollower',as: 'myfollowers'
  get '/followings/:id' => 'relationships#userfollowing',as: 'myfollowings'
  get '/search' => 'searches#search',as: 'search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
    validates :title, {presence: true}
	validates :body, {presence: true,length:{maximum:200}}
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, {presence: true}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
	# validates_uniquness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	belongs_to :follow, class_name: 'User'
	validates :user_id, presence: true
	validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  validates :name,{presence: true,length:{in: 2..20}}
  validates :introduction,{length:{maximum: 50}}

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_in_path_for(resource)
		user_path(current_user.id)
	end
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
	end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
		#対象のbookの情報を取得
		@book = Book.find(params[:book_id])
		#コメントはログインしているユーザがするよ。空のモデルを作る事でコメントの情報が入るよ。
		@book_comment = current_user.book_comments.new(book_comment_params)
		#コメントは何に対してするの？　＝　本に対してだよ。
		@book_comment.book_id = @book.id
		#コメントをセーブするよ
		@book_comment.save
		redirect_to book_path(@book.id)
	end
	def destroy
		@book_comment = BookComment.find(params[:book_id])
		@book = @book_comment.book
		if @book_comment.destroy
			#「.」リレーション、結びついた物を取り出す為に使う。
		   redirect_to request.referer
		end
	end

	def book_comment_params
    params.require(:book_comment).permit(:user_id,:book_id,:comment)
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_correct_user, {only: [:edit,:update,]}

	def index
		@user = current_user
		@book = Book.new
		@books = Book.all
	end

	def edit
		@book = Book.find(params[:id])
	end

	def show
		@book = Book.new
		@booked = Book.find(params[:id])
		@user = User.find(@booked.user_id)
		@book_comment = BookComment.new
		@book_comments = @booked.book_comments
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
		   flash[:success]='You have updated book successfully.'
		   redirect_to book_path(@book.id)
		else
		   render :edit
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	def create
		@book = Book.new(book_params)
		@book.user_id=current_user.id
		if @book.save
		   flash[:success]='You have creatad book successfully.'
		   redirect_to book_path(@book.id)
		else
		   @user = current_user
		   @books = Book.all
		   render :index
		end
	end

	def ensure_correct_user
		@book = Book.find(params[:id])
		if @book.user_id != current_user.id
			redirect_to books_path
		end
	end
	private
	def book_params
		params.require(:book).permit(:title,:body,:user_id)
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: book.id)
		favorite.save
		redirect_to request.referer
	end
	def destroy
		book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: book.id)
		favorite.destroy
		redirect_to request.referer
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
	def show
	end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @method = params[:search_method]
    @word = params[:search_word]
    @model = params[:book_or_user]
    @records = search_for(@model, @method, @word)
    #部分テンプレート先に新規投稿のフォームが存在する為book.newと定義しなければいけない
    @book = Book.new
  end

  private
  def search_for(model,method,word)
    if model == "book"
                if method == "forward_match"
                         Book.where("title LIKE?","#{word}%")
                elsif method == "backward_match"
                         Book.where("title LIKE?","%#{word}")
                elsif method == "perfect_match"
                         Book.where(title: "#{word}")
                elsif method == "partial_match"
                         Book.where("title LIKE?","%#{word}%")
                else
                         Book.all
                end
    elsif model == "user"
                if method == "forward_match"
                         User.where("name LIKE?","#{word}%")
                elsif method == "backward_match"
                         User.where("name LIKE?","%#{word}")
                elsif method == "perfect_match"
                         User.where(name: "#{word}")
                elsif method == "partial_match"
                         User.where("name LIKE?","%#{word}%")
                else
                         User.all
                end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def destroy
		super
		session[:keep_signed_out]= true
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_correct_user, {only:[:edit,:update]}
	def index
		@book = Book.new
		@users = User.all
		@user = current_user
	end
	def show
		@user = User.find(params[:id])
		@book = Book.new
		@books = @user.books
		current_user.book_comments
	end
	def edit
		@user = current_user
	end
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		   flash[:success]='You have updated user successfully.'
		   redirect_to user_path(@user.id)
		else
		   render :edit
		end
	end

	def ensure_correct_user
		@user = User.find(params[:id])
		if @user != current_user
		   redirect_to user_path(current_user.id)
		end
	end

    private
	def user_params
		params.require(:user).permit(:name,:profile_image,:introduction)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
        <p id="notice"></p>
      	<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Editing Book</h1>
    <% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <%= @book.errors.count %> errors prohibited this book from being saved:
      <h2>
        <% @book.errors.full_messages.each do |message| %>
      </h2>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
		<%= form_for(@book) do |f| %>
    <div class="field row">
      <label for="book_title">Title</label>
      <div class="col-xs-12">
      <%= f.text_field :title %>
      </div>
    </div>
    <div class="field row">
      <label for="book_opinion">Opinion</label>
      <div class="col-xs-12">
      <%= f.text_area :body %>
      </div>
    </div>
    <div class="actions row">
     <input type="submit" name="commit" value="Update Book" class="btn btn-primary col-xs-12" data-disable-with="Update Book">
    </div>
    <% end %>
    <%= link_to "Show", book_path(@book.id), class:"book" %> |
    <%= link_to "Back", books_path, class:"back" %>
  </div>
  <div class="col-md-3"></div>
</div>
</div>

app/views/books/index.html.erb
<%= render 'users/u', user: @user, book: @book %>

<div class="col-xs-9">
 <h1>Books</h1>
 <table class="table table-hover table-inverse">
   <thead>
     <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th></th>
       <th></th>
       <th colspan="3"></th>
     </tr>
   </thead>
   <tbody>
    <!-- eachでbookの全情報を取り出している -->
    <!-- いいねの情報も@books=Book.allで入手しているから、showの様に定義する必要ない -->
     <% @books.each do |book| %>
     <tr><td>
      <%= link_to user_path(book.user.id) do %>
      <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg' ,fallback:"no_image2.jpg" %></td>
      <% end %>
       <td><%= link_to book.title,book_path(book.id) %></td>
       <td><%= book.body %></td>
       <td>
         <% if book.favorited_by?(current_user) %>
           <%= link_to book_favorites_path(book), method: :delete do %>
             <%= fa_icon "fa fa-heart" %>
             <%= book.favorites.count %>
           <% end %>
         <% else %>
           <%= link_to book_favorites_path(book), method: :post do %>
             <%= fa_icon "fa fa-heart" %>
             <%= book.favorites.count %>
           <% end %>
         <% end %>
       </td>
       <td><%= link_to "コメント数:#{book.book_comments.count}", book_path(book.id) %></td>
     </tr>
       <% end %>
     </tbody>
 </table>
</div>

app/views/books/show.html.erb
<%= render 'users/u', user: @user, book: @book %>
<%= flash[:success] %>

<div class="col-xs-9">
<h1>Book detail</h1>
<table class="table">
<tbody>
	<tr>
		<td>
			<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback:"no_image2.jpg" %><br>
			<%= link_to @user.name, user_path(@user.id) %>
		</td>
		<td><%= link_to @booked.title, book_path(@booked.id) %></td>
		<td><%= @booked.body %></td>
		<td>
			<% if @booked.favorited_by?(current_user) %>
			  <%= link_to book_favorites_path(@booked),method: :delete do %>
			    <%= fa_icon "fa fa-heart" %>
			    <%= @booked.favorites.count %>
			  <% end %>
			<% else %>
			  <%= link_to book_favorites_path(@booked), method: :post do %>
			    <%= fa_icon "fa fa-heart" %>
			    <%= @booked.favorites.count %>
			  <% end %>
			<% end %>
		</td>
		<td>コメント数:<%= @booked.book_comments.count %></td>
		<% if @user == current_user %>
		<td><%= link_to "Edit", edit_book_path(@booked.id), class:"btn-sm btn-success" %></td>
		<td><%= link_to "Destroy", book_path(@booked.id), class:"btn-sm btn-danger",method: :delete, data:{confirm: '本当に消しますか？'}%></td>
		<% end %>
	</tr>
</tbody>
</table>


<%= form_for [@booked, @book_comment] do |f| %>
    <div class="row">
        <div class="col-sm-12">
            <%= f.text_area :comment, rows:'5', class: "form-control" %>
        </div>
    </div>
    <%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>
<div class="col-sm-12">
<% @book_comments.each do |book_comment| %>
  <%= book_comment.user.name %>
  <%= book_comment.created_at.strftime('%Y/%m/%d') %>
  <%= book_comment.comment %>
<% if book_comment.user_id == current_user.id %>
<%= link_to "削除", book_book_comments_path(book_comment), method: :delete, data: {confirm:'削除してもよろしいですか？'} %>
<% end %>
<% end %>
</div>
</div>

app/views/users/_error_messages.html.erb
<% if book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <%= book.errors.count %> errors prohibited this book from being saved:
      <h2>
      	<% book.errors.full_messages.each do |message| %>
      </h2>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_u.html.erb
<%= render 'users/error_messages', book: book %>
<div class="col-xs-3">
<h1>User info</h1>
<%= attachment_image_tag user, :profile_image, :fill, 100,100,format: 'jpeg', fallback:"no_image3.jpg" %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th>
        <%= link_to user.followings.count, myfollowings_path(user.id) %>
      </th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to user.followers.count, myfollowers_path(user.id) %>
      </th>
    </tr>
  </tbody>
</table>

<div class="row">
  <%= render 'relationships/follow_button', user: user %>
  <%= link_to "", edit_user_path(current_user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
</div>
  <h1>New book</h1>
  <%= form_for(book) do |f|%>
  <div class="field row">
    <h4>Title</h4>
    <%= f.text_field :title %>
  </div>
  <div class="field row">
    <h4>Opinion</h4>
    <%= f.text_area :body %>
  </div>
  <div class="action row">
    <input type="submit" name="commit" value="Create Book" class="btn btn-primary col-xs-12" data-disable-with="Create Book">
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
	<p id="notice"></p>
      <h1>User info</h1>
      <% if @user.errors.any? %>
       <div class="alert alert-warning">
        <h2>
         <%= @user.errors.count %> errors prohibited this book from being saved:
       </h2>
       <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
      <%= form_for(@user) do |f| %>
  <div class="field">
      <h4>Name</h4>
      <%= f.text_field :name %>
  </div>
  <div class="field">
      <h4>Image</h4>
      <%= f.attachment_field :profile_image %>
  </div>
  <div class="field">
      <h4>Introduction</h4>
      <%= f.text_area :introduction %>
  </div>
  <div class="actions">
      <%= f.submit 'Update User'%>
  </div>
      <% end %>
</div>
</div>

app/views/users/index.html.erb
<div class="row">
<%= render 'users/u', user: @user, book: @book %>

<div class="col-xs-9">
<h2>Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
    <tr>
    <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback:"no_image2.jpg" %></td>
      <td><%= user.name %></td>
      <!-- ユーザモデルでhas_many followingsとしている為この書き方可能 -->
      <td>フォロー数:<%= user.followings.count %></td>
      <!-- フォロワー数:<%#= Relationship.where(user_id: user.id).count %>と一緒 -->
      <td>フォロワー数:<%= user.followers.count %></td>
      <td>
        <% unless current_user == user %>
          <% if current_user.following?(user) %>
            <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: {method: :delete}) do |f| %>
      　　　  <%= hidden_field_tag :follow_id, user.id %>
             <%= f.submit 'フォロー外す' %>
            <% end %>
          <% else %>
            <%= form_for(current_user.relationships.build) do |f| %>
             <%= hidden_field_tag :follow_id, user.id %>
             <%= f.submit 'フォローする' %>
            <% end %>
          <% end %>
        <% end %>
      </td>
      <td><%= link_to "Show",user_path(user.id) %></td>
    </tr>
      <% end %>
    </tbody>
</table>
</div>
</div>

app/views/users/show.html.erb
<%= render 'users/u', user: @user, book: @book %>
  <%= flash[:success] %>
  <% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<div class="col-xs-9">
    <h1>Books</h1>

    <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
        <% @books.each do |book| %>
      <tr>
        <td><%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback:"no_image2.jpg" %></td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td>コメント数:<%= current_user.book_comments.count %></td>
      </tr>
        <% end %>
  </tbody>
</table>
</div>