config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to => 'homes#top'
  get '/home/about' => 'homes#show'

  resources :users, only:[:index,:show,:edit,:update,:create]
  resources :books, only:[:new,:create,:index,:show,:edit,:update,:destroy]
  resources :relationships, only:[:create,:destroy]
  resources :books, only:[:new,:create,:index,:show,:destroy] do
  	resource :favorites, only:[:create, :destroy]
  	resource :book_comments, only:[:create,:destroy]
  end
  get '/followers/:id' => 'relationships#userfollower',as: 'myfollowers'
  get '/followings/:id' => 'relationships#userfollowing',as: 'myfollowings'
  get '/search' => 'searches#search',as: 'search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
    validates :title, {presence: true}
	validates :body, {presence: true,length:{maximum:200}}
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, {presence: true}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
	# validates_uniquness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	belongs_to :follow, class_name: 'User'
	validates :user_id, presence: true
	validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  validates :name,{presence: true,length:{in: 2..20}}
  validates :introduction,{length:{maximum: 50}}

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_correct_user, {only: [:edit,:update,]}

	def index
		@user = current_user
		@book = Book.new
		@books = Book.all
	end

	def edit
		@book = Book.find(params[:id])
	end

	def show
		@book = Book.new
		@booked = Book.find(params[:id])
		@user = User.find(@booked.user_id)
		@book_comment = BookComment.new
		@book_comments = @booked.book_comments
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
		   flash[:success]='You have updated book successfully.'
		   redirect_to book_path(@book.id)
		else
		   render :edit
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	def create
		@book = Book.new(book_params)
		@book.user_id=current_user.id
		if @book.save
		   flash[:success]='You have creatad book successfully.'
		   redirect_to book_path(@book.id)
		else
		   @user = current_user
		   @books = Book.all
		   render :index
		end
	end

	def ensure_correct_user
		@book = Book.find(params[:id])
		if @book.user_id != current_user.id
			redirect_to books_path
		end
	end
	private
	def book_params
		params.require(:book).permit(:title,:body,:user_id)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
	def show
	end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @method = params[:search_method]
    @word = params[:search_word]
    @model = params[:book_or_user]
    @records = search_for(@model, @method, @word)
    #部分テンプレート先に新規投稿のフォームが存在する為book.newと定義しなければいけない
    @book = Book.new
  end

  private
  def search_for(model,method,word)
    if model == "book"
                if method == "forward_match"
                         Book.where("title LIKE?","#{word}%")
                elsif method == "backward_match"
                         Book.where("title LIKE?","%#{word}")
                elsif method == "perfect_match"
                         Book.where(title: "#{word}")
                elsif method == "partial_match"
                         Book.where("title LIKE?","%#{word}%")
                else
                         Book.all
                end
    elsif model == "user"
                if method == "forward_match"
                         User.where("name LIKE?","#{word}%")
                elsif method == "backward_match"
                         User.where("name LIKE?","%#{word}")
                elsif method == "perfect_match"
                         User.where(name: "#{word}")
                elsif method == "partial_match"
                         User.where("name LIKE?","%#{word}%")
                else
                         User.all
                end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def destroy
		super
		session[:keep_signed_out]= true
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :ensure_correct_user, {only:[:edit,:update]}
	def index
		@book = Book.new
		@users = User.all
		@user = current_user
	end
	def show
		@user = User.find(params[:id])
		@book = Book.new
		@books = @user.books
		current_user.book_comments
	end
	def edit
		@user = current_user
	end
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		   flash[:success]='You have updated user successfully.'
		   redirect_to user_path(@user.id)
		else
		   render :edit
		end
	end

	def ensure_correct_user
		@user = User.find(params[:id])
		if @user != current_user
		   redirect_to user_path(current_user.id)
		end
	end

    private
	def user_params
		params.require(:user).permit(:name,:profile_image,:introduction)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Home", user_path(current_user), class:"glyphicon glyphicon-home home" %></li>
          <li><%= link_to "Users", users_path, class:"glyphicon glyphicon-user users" %></li>
          <li><%= link_to "Books", books_path, class:"glyphicon glyphicon-book books" %></li>
          <li><%= link_to "logout", destroy_user_session_path,method: :delete, class:"glyphicon glyphicon-log-out logout" %></li>
       <div class="search_nav">
          <%= form_tag(search_path , method: :get) do %>
          <%= text_field(@search_content, :search_word)%>
          <%= select(@search_content, :book_or_user, [["Book","book"], ["User","user"]])%>
              <%= select(@search_content, :search_method, [["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]])%>
              <%= submit_tag "検索" %>
      　　<% end %>
       </div>
        <% else %>
        <li><%= link_to "Home", "/", class:"glyphicon glyphicon-home home" %></li>
          <li><%= link_to "About", home_about_path,class:"glyphicon glyphicon-link about" %></li>
          <li><%= link_to "sign up", new_user_registration_path, class:"glyphicon glyphicon-edit sign_up" %></li>
          <li><%= link_to "login", new_user_session_path, class:"glyphicon glyphicon-log-in sign_in" %></li>
          <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %><br><br><br>
  <div class="container">
  <div class="row">
    <%= yield %>
  </div>
  </div>
    <%= render "layouts/footer" %>
  </body>
</html>